# ----------- CONFIGURABLE START -----------
title:            "LPC-DM Analysis Group"
description:      "Lasciate ogni speranza, voi ch'entrate."
url:              "https://lpc-dm.github.io" # Site url, without a slash at the end.
signoff:          "mcremone" # Your name
facebook_appid:   # APP ID for like button, remove from /_includes/share.html if unwanted.
google_analytics: # Set tracking, remove from /javascripts/basic.js if unwanted.
share:            false # Turn on twitter and facebook share buttons

links:
  - name:         Overview & Projects
    url:          /overview
    external:     false
  - name:         Software
    url:          /software
    external:     false
  - name:         Meetings
    url:          /meetings
    external:     false
  - name:         Communication
    url:          /communication
    external:     false
  - name:         Members
    url:          /members
    external:     false

    
# ------------ CONFIGURABLE END ------------

permalink:        /posts/:title
defaults:
  - values:
      layout: "default"
theme: jekyll-theme-slate

# ------------ BUILD SETTINGS ------------
markdown: kramdown

# ------------ CONFIGURABLE DEFAULTS ------------

github: [metadata]
encoding: UTF-8	
kramdown:
  input: GFM
  hard_wrap: false
future: true
jailed: false
gfm_quirks: paragraph_end

# ------------ CONFIGURABLE DEFAULTS ------------

lsi: false
safe: true
source: .
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge